### ISSUE TITLE
While executing a NiFi job asking for Input Port

### ISSUE THREAD

**Issue by sanjiv1980** [B23admin/nifi-stateless-operator#4]
I am new to NiFi world and that to NiFi-Fn it's very new , I have gone through documentation and deployed the same on EKS (AWS) cluster . While executing NiFi job (any job) , It throwing exception like `input port is missing` , not able to understand why it's required ? 

Note: Is the case of RPG ..? could you please explain and better if you attach one simple template , that will great help

```
kubectl logs nififn-listing-s3-job-tf6sg -n nifi-fn-operator-system
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/nifi-1.8.0/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/nififn/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/nififn/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "main" java.lang.IllegalArgumentException: Flow does not have an input port...
	at org.apache.nifi.fn.core.FnFlow.enqueueFlowFile(FnFlow.java:254)
	at org.apache.nifi.fn.runtimes.Program.main(Program.java:88)
```

**Comment by dbkegley** [comment]
For nifi-fn to initialize properly there must be a single input port at the root level of the NiFi canvas.  Any flowfiles defined in the `flowFiles` field of the manifest will be sent to this input port and processed by the flow

```yaml
flowFiles:
  - "absolute.path-/path/to/input/data/;filename-testfile.txt"
```

**Comment by sanjiv1980** [comment]
Hi @dbkegley , Just wanted to know like while submitting a job we are using the docker images 
```
apiVersion: nififn.b23.io/v1alpha1
kind: NiFiFn
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nififn-file
  namespace: nifi-fn-operator-system
spec:
 ``` image: "samhjelmfelt/nifi-fn:latest"```
  registryUrl: "http://registry-service:18080"
  bucket: "37602fe6-0d58-4179-a34a-aa3c494a6cca"
  flow: "16887b00-9669-4c6c-8991-03ac6e6c24be"
  flowVersion: 1
  flowFiles:
  - "absolute.path-/opt/nifi/nifi-current/test/input/;filename-a.txt"
```

How is it different from NiFi-Stateless..? Better If you could describe it.
